### ISSUE TITLE
Editor not working when BridgeX connected to power

### ISSUE THREAD

**Issue by imranino** [Pirate-MIDI/Pirate-MIDI-BridgeOS#103]
**Device:**
 - Device: Bridge6 and 4, mac OS 11 big Sur
 - Firmware version: latest
 - Hardware version:  v1.0

**Describe the bug**
In order to use the editor, i need to unplug the BridgeX from my power supply. Not a biggy, but a slight inconvenience.

**To Reproduce**
1. pedalboard is powered on as normal
2. Plug into computer via USB cable, with no intermediary hub
3. open the editor in chrome, no devices available
4. Unplug 9v. power input from bridgeX
5. bridge appears as a selectable device in the editor

**Expected behavior**
As above, without having to unplug the power supply

**Comment by simonaglover95** [comment]
Hi Imran, 

This is a consequence of how USB works, and depending on the device, this is just a necessary part of the process and can't be fixed. The USB controller detects a device is connected by the fact that it's drawing current. If all the power is being supplied by the DC power, then the USB isn't drawing enough to register as a connected device on the computer. 

As you say, removing the DC jack for working with the USB is the solution if you come across this. 

Cheers,
Simon
