### ISSUE TITLE
Editor stuck on "Synchronising Banks" at 24%

### ISSUE THREAD

**Issue by emilyperry456** [Pirate-MIDI/Pirate-MIDI-BridgeOS#113]
**Device(please complete the following information):**
 - Device: Bridge6
 - Firmware version: 1.1.1
 - Hardware version: v1.0.1

**Describe the bug**
In the editor app using Chrome version 108.0.5359.94 (Official Build) (x86_64) on 2018 Mac Mini, my device freezes and the editor cannot make it past 24% when "synchronising banks."

**To Reproduce**
1. Open the editor site
2. Click import from device and select Bridge6

**Expected behavior**
The initialization process will begin and the editor will get stuck at 24%.

**Comment by samspencer5991** [comment]
Thanks for that @emilyperry456. We'll need a lot more information to help diagnose the problem though.

For example, what settings have been changed?

You're on an out dated firmware version. Have you tried updating the firmware first? Note that moving from v1.1 to v1.2 requires a factory reset in between.

**Comment by samspencer5991** [comment]
@emilyperry456 any further updates on this or can I mark this as solved?
