### ISSUE TITLE
Bridge 4 Device Link Flexi2 will not set to Device Link if Bridge 6 Device Link is set to "Main"

### ISSUE THREAD

**Issue by Eldritch-Tentacles** [Pirate-MIDI/Pirate-MIDI-BridgeOS#116]
**Device(please complete the following information):**
 - Device: Bridge 4
 - Firmware version: 1.2.0
 - Hardware version: 1.0.1

**Describe the bug**
If Bridge 4's Flexiport 2 is connected to Bridge 6 (Flexiport 1 ) and Bridge 6 is set as "Main" in the Device Link; When setting Flexiport 2 to Device Link it will automatically revert to EXP.  

**To Reproduce**
1. With Bridge 6 set to Device Link as "Main"
2. Go to Global -> Flexiports -> Flexiport2
3. Set Mode to "Device Link" 
4. Return to main screen, Flexiport 2 will show expression pedal graphic
5. Go to Global -> Flexiports -> Flexiport2
6. See Bridge4 will have reverted back to saying EXP
7. Try the steps above with Bridge 6 set to "Sat." (or with nothing plugged into Flexiport 2)
8. See Bridge 4 Flexiport2 will show Device Link graphic but won't connect to Bridge 6
9. Change Bridge 6 back to "Main"
10. See Bridge 4 graphic show both EXP graphic over Device Link graphic
11. Go to Global -> Flexiports -> Flexiport2
12. See Bridge 4 will have reverted back to saying EXP

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by simonaglover95** [comment]
Looks like this is solved in v1.2.1 @Eldritch-Tentacles ?
