### ISSUE TITLE
Bridge6 will only connect to Bridge4 via Device Link if Bridge6 is "Main"

### ISSUE THREAD

**Issue by Eldritch-Tentacles** [Pirate-MIDI/Pirate-MIDI-BridgeOS#117]
**Device(please complete the following information):**
 - Device: Bridge6
 - Firmware version: v1.2.0
 - Hardware version: v1.1.2

**Describe the bug**
Bridge6 will only seem to connect to Bridge4 via Device Link if Bridge6 is "Main" and Bridge4 is "Sat."
Reversing rolls; where Bridge4 is "Main" and Bridge4 is "Sat." will result in Bridge6 Device Link graphic displaying the "S" but will show the block not filled in and no communication between the two. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by simonaglover95** [comment]
Working in v1.2.1 - closing this issue.
