### ISSUE TITLE
While Device Linked; Bridge6 will not thru MIDI from Bridge4 to MIDI chain. 

### ISSUE THREAD

**Issue by Eldritch-Tentacles** [Pirate-MIDI/Pirate-MIDI-BridgeOS#118]
**Device(please complete the following information):**
 - Device: Bridge6
 - Firmware version: v1.2.0
 - Hardware version: v1.1.2

**Describe the bug**
Using Device Link; where Bridge4 (Flexiport1 - Sat.) is connected to Bridge6 (Flexiport1 - Main), the two devices will communicate but MIDI commands coming from Bridge4 via Flexiport will not be transmitted thru Bridge6 Din down to MIDI devices. 

**To Reproduce**
1. Connect Bridge4 Flexiport1 to Bridge6 Flexiport1 via TRS cable
2. Set Flexiport1 of both devices to Device Link
3. Set Device Link of Bridge4 to Sat. and Bridge6 to Main
4. Set Bridge6 Midi Thru Routing coming from Flexi1 to Din
5. Create MIDI command from Bridge4 with Output Message to Flexi1 
6. MIDI command will not transmit through Bridge6 Din to MIDI chain. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by simonaglover95** [comment]
@Eldritch-Tentacles I've checked this out and it seems you've missed the step of setting the Device Link settings on each device for "MIDI Rx" to "On" :) on fw v1.2.1 it's working fine for me with your exact setup when accounting for this setting being turned on. 

Cheers,
Simon
