### ISSUE TITLE
Bank Drop Down List doesn't change selected bank

### ISSUE THREAD

**Issue by sliberty** [Pirate-MIDI/Pirate-MIDI-BridgeOS#127]
**Device(please complete the following information):**
 - Device: Bridge 6
 - Firmware version: 1.2.1
 - Hardware version: 1.1.3

**Describe the bug**
Dropping the bank list down on the main screen and selecting a different bank DOES NOT change which bank is shown on this screen. The up and down arrow buttons next to the bank drop down list DOES work as expected.

**To Reproduce**
1. Drop down the list, and select a different bank

**Expected behavior**
Displayed bank should change to the one selected in the drop down list

**Screenshots**
![image](https://user-images.githubusercontent.com/3092162/216845098-6af9a325-b2e8-427e-bd7c-6c076438f6d5.png)
In this screen shot, the drop down list currently displays bank 8.

**Additional context**

**Comment by sliberty** [comment]
I tested in the beta web app AND the beta "installed" app, and it behaved the same way in both.

**Comment by samspencer5991** [comment]
@Konnsalad

**Comment by Konnsalad** [comment]
A fix for this was pushed a few weeks ago, can you give it a test for me please @sliberty and confirm that it's working as expected for you now.

**Comment by sliberty** [comment]
Working as expected. Thanks for applying this fix.
