### ISSUE TITLE
Scrolling Message(s) are not triggered by Secondary Action.

### ISSUE THREAD

**Issue by TheOcelot42** [Pirate-MIDI/Pirate-MIDI-BridgeOS#135]
**Device(please complete the following information):**
 - Device: Bridge 6
 - Firmware version: 1.2.1
 - Hardware version: 1.1.3

Summary:

  I am having an issue getting my Scrolling footswitches to send on their Seconday Action.
  I have also seen an odd behavior where an unassociated FS press can decrement a "Scrolling" FS in the same bank.
  
**To Reproduce**

1. See configuration below for setup steps.
2. Factory reset the DUT
3. From the editor, send the configuration to the device.
4. SINGLE press FS2 a few times to ensure its scroll counter is incremented.
5. SINGLE press FS1 a few times to ensure its scroll counter is incremented.
6. DOUBLE press FS2
7. SINGLE press FS1
8. Press and Hold FS1.

**Expected behavior**

- The double press at Step 6 should have triggered the CC message in FS2's Scrolling list.
- The final single press on FS1 should have incremented its Scroll counter.
- The press and hold on FS1 should have triggered the CC message in FS1's Scrolling list.

**Actual results:**

- The DOUBLE press on FS2 never emits a CC message.
- The final SINGLE press on FS1 DECREMENTS the scroll counter of FS2.
- The PRESS AND HOLD on FS1 never emits a CC message.

<img width="1286" alt="ScrollTest_Switch1_Config" src="https://user-images.githubusercontent.com/56091421/219974903-6aee4f5f-b208-411d-bb49-b1006691aa0b.png">
<img width="1293" alt="ScrollTest_Switch1_Messages" src="https://user-images.githubusercontent.com/56091421/219974904-8cee3c82-e6d4-483f-a032-37eb0c89e725.png">
<img width="1284" alt="ScrollTest_Switch2_Config" src="https://user-images.githubusercontent.com/56091421/219974906-c4b8b335-be00-4b83-a044-4a3b092819a3.png">
<img width="1294" alt="ScrollTest_Switch2_Messages" src="https://user-images.githubusercontent.com/56091421/219974909-68057a74-0003-4540-8e0e-4f2ab9bd0505.png">

**Comment by samspencer5991** [comment]
Fixed in v1.2.2
