### ISSUE TITLE
"Scrolling" FS Labels can overlap.

### ISSUE THREAD

**Issue by TheOcelot42** [Pirate-MIDI/Pirate-MIDI-BridgeOS#136]
**Device(please complete the following information):**
 - Device: Bridge6
 - Firmware version: 1.2.1
 - Hardware version: 1.13

**Describe the bug**
If two or more horizontally adjacent footswitches are:
1. configured to "Scroll",
2. have a label using the maximum number of characters (8)

When the scroll index is appended to the label, it causes an overlap
with its adjacent label.

**To Reproduce**
Testing assumptions:
0. Factory reset the DUT
1. Restore the attached example config onto the DUT.

Steps to reproduce:
1. Press FS6. Note the index displayed.
2. Press FS3. Note the index displayed.
2. Press FS1. Note the index displayed.

**Expected behavior**
All of the index values should be legible.

**Actual results**

The labels will overlap, and the indices of all but the RIGHT most switches (FS6, 3) 
will be obscured.

**Screenshots**
See attached screenshot + QuickTime.

**Additional context**
Discussion:

This effectively limits the size of the scrolling label to 4 characters.  Would it be in possible
to use the smaller text size that "Sequential" uses? 

For bonus points: Can we have adaptively sized text (I am willing to trade size for character count)

https://user-images.githubusercontent.com/56091421/219981677-60122be5-c7a1-445c-913e-24a6567f0136.mov

![ScrollingLabelsOverlap](https://user-images.githubusercontent.com/56091421/219981791-82b1bf0a-6e2a-4115-9581-bee48259511c.png)

**Comment by samspencer5991** [comment]
Fixed in v1.2.2
