### ISSUE TITLE
LFO step size is half of set value (Ramp and Sawtooth)

### ISSUE THREAD

**Issue by frenno** [Pirate-MIDI/Pirate-MIDI-BridgeOS#141]
**Device**
 - Device: Bridge 6
 - Firmware version: v1.2.1 (has been factory reset)
 - Hardware version: 1.0.1

**Describe the bug**
The "step size" sent by the LFOs with Ramp or Sawtooth shape is half of what is set (except when it is set to 1).
Step size 2 in UI -> sends steps 1 value apart (0 1 2 3 4 etc)
Step size 4 in UI -> sends steps 2 apart
etc

Triangle shape works, Sine follows the step size for most of the range except near the min/max (this is fine as the time between sending values is further apart there). I guess it doesn't apply to square wave/random anyway.

**To Reproduce**
1. Add message to Toggle on stack
2. Set LFO to enabled, ramp or sawtooth shape, using toggle on stack, any value apart from 1 for step size
3. Press footswitch to turn on LFO
4. MIDI monitor shows step size half of what was set

**Comment by samspencer5991** [comment]
Fixed in v1.2.2
