### ISSUE TITLE
Web editor: bug in the edit function when all the 16 sequential message are added

### ISSUE THREAD

**Issue by MarkFSI** [Pirate-MIDI/Pirate-MIDI-BridgeOS#143]
In the last web editor version, just released a few days ago, I've noticed an odd behaviour while I try to edit a message when all 16 message available for sequential mode are been added: the editor doesn't let you to edit messages (saying "Maximum Messages Reached"), only let to delete one and add a new message.
The bug appears either thet the messages are all in the same step, or one for step, in 16 step.

I've noticed this bug using google chrome browser. I've not tested other browsers to check the this bug.

![Immagine 2023-02-23 233606](https://user-images.githubusercontent.com/126206524/221046271-ce6dab5b-4965-4159-b293-0f0fba5b49e5.jpg)

**Comment by samspencer5991** [comment]
Hey mate, great catch. I'll let @Konnsalad know

**Comment by Konnsalad** [comment]
Solved.
