### ISSUE TITLE
Emulated press (MIDI CC10-13 on B4) not working with MIDI Thru

### ISSUE THREAD

**Issue by imranino** [Pirate-MIDI/Pirate-MIDI-BridgeOS#147]
**Device:**
 - Device: [e.g. Bridge4]
 - Firmware version: [e.g. v1.2.1]
 - Hardware version: [e.g. v1.0]

**Describe the bug**
i'm using a secondary midi controller to send commands CC10-13, perfectly emulating the onboard footswitches. unfortunately, this only works when MIDI thru is OFF. When it's on, the footswitches appear to respond to the commands, but they fail to send the Midi message onwards.

**To Reproduce**
1. Send midi CC10-13 to the BridgeX. 
2. CC10-13 makes FS1-4 turn on, and send the midi messages programmed in, whatever the mode - toggle, momentary, sequential and tap tempo have all worked. 
3. Go to the menu>global>midi>midi thru and turn on TRS in>TRS out
4. CC10-13 makes FS1-4 turn on, but the programmed the midi messages don't send, whatever the mode - toggle, momentary, sequential. Tap tempo does work. 
5. Midi thru IS working as messages sent from another device are being received further down the midi chain.

**Expected behavior**
CC10-13 makes FS1-4 turn on, and send the midi messages programmed in, whatever the mode - toggle, momentary, sequential and tap tempo have all worked. Should work with or without MIDI thru.

**Screenshots**
check the videos I posted on the FB group yesterday and the day before.

**Comment by simonaglover95** [comment]
Fixed in BridgeOS 2.0 Release
