### ISSUE TITLE
Switch "Copy From" on device misses LFO "MESSAGES" field

### ISSUE THREAD

**Issue by frenno** [Pirate-MIDI/Pirate-MIDI-BridgeOS#155]
**Device**
 - Device: Bridge6
 - Firmware version: 1.2.1
 - Hardware version: 1.0.1

**Describe the bug**
When copying a switch using the on-device menu, the MESSAGES field of the LFO settings is not copied (other fields seem to all be copied correctly).

**To Reproduce**
1. Go to Menu > Switches > Switch 1 > LFO
2. Messages field is blank, set to Toggle On (or anything other than blank)
3. Menu > Switches > Switch 2 > Copy From and select switch 1
4. After device restart, go to Menu > Switches > Switch 2 > LFO and the MESSAGES field is blank

**Expected behavior**
MESSAGES field should be copied

**Comment by samspencer5991** [comment]
@frenno This is not so much a bug, but a limitation of the way that banks are stored and dynamically updated. Whilst it is technically possible to ensure that the target message stack is copied, it will require a non-trivial amount of development and testing and will also be very difficult to maintain in firmware revisions.

This copy function is also available in the editor and handled fully there so we will be adding a note to the user manual pointing out that if you're copying a switch including LFO assignment using the onboard navigation, the LFO message stack target must be manually set.
