### ISSUE TITLE
Go to bank control message kills serial communication

### ISSUE THREAD

**Issue by GriffinSauce** [Pirate-MIDI/Pirate-MIDI-BridgeOS#156]
**Device details**
```
{
  deviceModel: 'Bridge6',
  firmwareVersion: '1.2.1',
  hardwareVersion: '1.0.1',
  uId: '4d00344d00384d003c',
  deviceName: 'Bridge 6',
  profileId: '0'
}
```

**Describe the bug**
This is a bug that happened before and seems to be back: when I send one goToBank command, the serial connection stops responding until the device is restarted.

**To reproduce**
Send:
```
0,CTRL~
1,goToBank,2~

-> no response, API is ded
```
<img src="https://media.giphy.com/media/qH7J4EXzSCmBy/giphy.gif" width="480" height="349" />

I've been able to reproduce it using raw commands with https://www.serialterminal.com/ and a factory reset does not help. So I don't think it has anything to do with my surrounding code or configuration.

**Comment by simonaglover95** [comment]
Fixed in BridgeOS 2.0 Release
