### ISSUE TITLE
MS Relay

### ISSUE THREAD

**Issue by ChuckBarnard** [Pirate-MIDI/Pirate-MIDI-BridgeOS#160]
**Device(please complete the following information):**
 - Device: Bridge6
 - Firmware version: 1.2.2
 - Hardware version: 1.0.1

**Describe the bug**
Relay does not appear to be working to control a MS Relay whether I select it in the web editor or on the device itself

**To Reproduce**
Global Settings - Flexiport Settings - Flexiport 2 Mode: Relay Out
Bridge 6 UI shows Flxiport 2 as an expression pedal symbol.

On the bridge 6 if I change it to relay it shows Flexiport 2 as a folic symbol on the main UI but the web editor shows that it is not configured.
Setting at either place does not provide the option for the relay out as a Smart Message.

**Expected behavior**
I believe I should be able to add Smart Messages to switch commands that would manage the MorningStar Omniport Relay.

**Screenshots**

**Additional context**

**Comment by samspencer5991** [comment]
Fixed in v1.3.0
