### ISSUE TITLE
Request for switch configuration 

### ISSUE THREAD

**Issue by Eldritch-Tentacles** [Pirate-MIDI/Pirate-MIDI-BridgeOS#161]
Would it be possible to have a switch configuration where you had the primary toggle "On" on the first press (Primary LED comes on), the secondary toggle "On" on the second press (Secondary LED comes on, Primary LED stays on), and then toggle off on the third press (Both LEDs go off)?

By way of example; you could have an added Primary Switch Mode setting of "First Press Toggle" and a Secondary Switch Mode setting of "Second Press Toggle"

A second request ( I can put this as separate if requested) would be to have an option for turning off the "Toggle Off" function on the Primary function of a switch. Just on the switch's action itself but still be "toggled off", via the Switch Groups, by toggling other switches "On".
An exampled use case for this would be, anecdotally; I have Switch 1 on my Bridge 6 set to my most used "Home sound"... it sets my amp to my lead channel, activates one pedal on a specific preset , and sets 4 other pedals to useful presets but bypassed.
It would be really handy to be able to activate one (or more) of the "pedals in waiting" (via the pedals' own bypass switches) and then have it go right back to the basic settings of Switch 1 by pressing switch 1 again.
I do this now but I have to press it twice to come back to the "Toggle On" status.

Thanks for your efforts and patience fellas!

**Comment by simonaglover95** [comment]
for the second feature, why not just use sequential mode, with two steps (or one? I've never tried with one) so that every time you press, it goes to the next step (identical) and then keeps going round the cycle...

**Comment by Eldritch-Tentacles** [comment]
@simonaglover95 I wouldn't want to use the sequential mode because I still would like it to mostly act like the toggle on setting. I.e. I press switch one, it sends the toggle on messages, the light comes on and stays on which gives me quick visual feedback that that's still where I am while playing live. I hit switch three, the toggle messages of three are sent, switch three light comes on/stays on, switch one light goes off. 
The Toggle setting works for me perfectly with the switch groups with the exception that I never toggle a switch off using the switch itself. Togglng off a switch is always done, for me, by toggling another switch on. 

What would be far more handy to me, instead of using sequential is just having the option to defeat the "toggle off" function of a switch so that pressing it only toggles it on. 
An example would be: I press switch 1 and it toggles on, sends all of the toggle on commands.... perhaps I turn on one or more pedals (that were PC changed and bypassed in the original toggle commands)..... I'd love it if I could then simply  hit switch one again and it stays on and sends it's original toggle commands again. 
I do this now but I have to toggle it off and quickly toggle it back on. 
I'm hoping I'm conveying this correctly. 
Going to sequential overly complicates the whole idea and I wouldn't have the visual feedback of knowing which switch I'm on while performing.

**Comment by simonaglover95** [comment]
Do you know about the smart messages that toggle a switch on? I can't 100% visualise your setup (these things are usually quite specific) but I think I see what you're getting at. 

That smart message can be used anywhere and might be a help to what you're after :)

**Comment by Eldritch-Tentacles** [comment]
Okay.... Brilliant!.... Yes, the Smart Message did exactly what I was looking for. Thank you!
Although, I'm at a loss for understanding why the opposite message I would have thought would work, worked.
I set a "Press" Smart Message as "Switch Off", FS1, Primary. 

I'd have thought, to do what I wanted, it would have been a "Switch On" message.... but quickly noticed it simply kept the LED off. 
But.... at any rate.... it works exactly how I'd like.... Thanks again, my dudes.... for your time and patience.
