### ISSUE TITLE
Screen Display

### ISSUE THREAD

**Issue by deandonaldson** [Pirate-MIDI/Pirate-MIDI-BridgeOS#164]
In the web editor it shows one less character compared to what you can actually have on the device.

Though it scrolls through, be better to extend the middle screen by one character to accurately reflect the device.

**Comment by samspencer5991** [comment]
Hey @deandonaldson I can't replicate this. Are you saying that you can only enter in 15 characters on the web editor compared to the 16 you are allowed?

**Comment by deandonaldson** [comment]
Hey @samspencer5991 

When you type into the editor it scrolls for the last character. You can physically enter it, but visually it doesn't show. It threw me originally as thought I was out of characters until I realised it wa just a design bug. 

I guess if you reduce font size a couple of points or enrage screen area on editor it would correct this?
