### ISSUE TITLE
Can't disable both bank triggers

### ISSUE THREAD

**Issue by GriffinSauce** [Pirate-MIDI/Pirate-MIDI-BridgeOS#176]
**Device(please complete the following information):**
 - Device: Bridge6
 - Firmware version: v1.0.1
 - Hardware version: v1.2.4

**Describe the bug**
It's not possible to disable both bank triggers:

**To Reproduce**
- Set both bank up and down triggers to "None"

**Expected behavior**
It disables both triggers.

**Screenshots**
<img width="355" alt="CleanShot 2023-03-26 at 21 55 23@2x" src="https://user-images.githubusercontent.com/5630996/227801265-4a32b95d-f712-4b7c-bd3e-e7a4f6746001.png">

**Additional context**
I have a dual aux switch to do bank switches, it should be possible to disable the triggers on the device completely.
This might just be an editor input-validation bug.

**Comment by samspencer5991** [comment]
Absolutely just an input validation error. As you would expect, it won't let you make both triggers the same thing, but there obviously needs to be an exception for the none option. @konnsim

**Comment by konnsim** [comment]
@GriffinSauce thanks for picking that up, just pushed a hotfix.

**Comment by GriffinSauce** [comment]
Thanks @konnsim, works now!
