### ISSUE TITLE
Web Editor Update - Unable to Connect Bridge4

### ISSUE THREAD

**Issue by Glennmack** [Pirate-MIDI/Pirate-MIDI-BridgeOS#179]
**Device(please complete the following information):**
 - Device: Bridge4
 - Firmware version: v1.2.2
 - Hardware version: [e.g. v1.0]

**Describe the bug**
I went to =connect my iMac to the Bridge4 within Chrome. On connection, I was prompted to use a newer version of the web editor. I accepted, then I get the following error message. Computer restart didn't fix the issue. 

<img width="437" alt="image" src="https://user-images.githubusercontent.com/128812448/230711348-e9641735-3baa-426e-8226-57086d54af26.png">

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="437" alt="image" src="https://user-images.githubusercontent.com/128812448/230711373-cd8fa0a5-fd94-4f28-91f9-47bda3e99fc5.png">

**Additional context**

**Comment by samspencer5991** [comment]
There have been 3 newer firmware versions since v1.2.2. Please ensure you are running the latest version of BridgeOS before creating an new issue.

**Comment by Glennmack** [comment]
Hi Sam

My problem is that I can’t seem to get the Bridge4 to connect at all - no problems until today. I’ve installed the latest Updater but it doesn’t see the Bridge4 at all.

Cheers

Glenn

**Comment by samspencer5991** [comment]
Ok no worries, that's a completely separate issue though.

We're working on a fix where the updater won't recognise devices with a Custom device name. So either factory reset your device, or reset your device name to Bridge6 or Bridge4 (try with and without the spaces), and you shouldn't have any issues. You can always update your firmware using the manual method by following the instructions on our website on the firmware page.

**Comment by Glennmack** [comment]
Hi Sam

I needed to reset the unit, renaming didn’t work as it kept reverting to the custom name, even though it said it saved the change.

Another problem - I now get this screen. I have the latest version ion Chrome installed, the latest firmware and the latest Updater.

Any ideas?

Glenn

**Comment by samspencer5991** [comment]
Your picture hasn't come through, but I'm going to assume that you just need to perform the factory reset as required after the firmware update :)

**Comment by Glennmack** [comment]
Factory Reset was completed. Unfortunately I’m back to my original problem.

**Comment by samspencer5991** [comment]
Ok, could you please open to chrome console (F12) and copy the contents of the console when this occurs?

**Comment by Glennmack** [comment]
I’m not familiar with Chrome Console - can’t find anything on the Mac. Any tips?

**Comment by samspencer5991** [comment]
All good, press F12 and a little window will open up on the right. Click on the console tab and copy the contents

**Comment by Glennmack** [comment]
Here tis, I needed to enable standard function keys:

:

**Comment by samspencer5991** [comment]
I can't see any console logs attached mate, could you confirm please?

**Comment by Glennmack** [comment]
Screenshot:

**Comment by Glennmack** [comment]
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/128812448/230715345-14a2ad80-96ae-4e5d-be68-be1ed4250149.png">

**Comment by samspencer5991** [comment]
@konnsim

**Comment by Glennmack** [comment]
I'm done for the night Sam. The latest is I used an older Web Editor link and got as far as trying to update the now rest Bridge4. It gets as far as 15% and then freezes like this. 

<img width="544" alt="image" src="https://user-images.githubusercontent.com/128812448/230716224-24cd2488-fd94-45ae-9509-bfbd490e0156.png">

**Comment by samspencer5991** [comment]
No worries mate, we'll get this sorted out asap for you. Could you please export your config file from the editor and email it to us and I'll get it looked at first thing next week

**Comment by Glennmack** [comment]
Thanks Sam

I've had a little success, this involved reverting to Firmware v1.2.2. 

I then managed to get the Web Editor to open my backup file, I've tried to attach this below but it seems the file type isn't accepted here - I'll try emailing it. When I loaded this file, the names of all of the switches and banks were whited out as shown above, but by going into Global settings and out again, the text all appeared as normal (i.e. white text on dark background). However, I couldn't export this file back to the Bridge4. It kept sending up the error message.

To overcome this, I opened Web Editor in two windows, I copied each bank (bank by bank) to the clipboard, then pasted it into a new file. I was then able to send this new .json file to the Bridge4. 

So, I am now set up with v1.2.2, have managed to rescue my many banks (a lot of time went into these so I'm relieved), and have saved as a new exported .json file. Note though, when I load this file ('Import From File') the text is again whited out until I go into Global Settings and out again. 

Cheers

Glenn

**Comment by Glennmack** [comment]
Sam

Here is the exported file that I’ve been having trouble with.

Cheers

Glenn

**Comment by Glennmack** [comment]
One last update - what I thought was success isn't actually success. The copied file has the same issues.

**Comment by konnsim** [comment]
Pushed a fix for the white boxes.

**Comment by Glennmack** [comment]
Thanks Kurtis. Will this also fix the issue related to connection to Bridge4? I’ve been unable to upload from and send to Bridge4 from the web editor since the latest update. Thanks. On 11 Apr 2023, at 2:35 pm, Kurtis Simpson ***@***.***> wrote:﻿
Pushed a fix for the white boxes.

**Comment by samspencer5991** [comment]
@Glennmack the white boxes was entirely unrelated mate, that was just a UI bug in the editor.

Coming back to your original issue. You've backed up your config, so that's good. I haven't received an email from you, nor is your config attached here. Can you please make sure you have sent it to sam@piratemidi.com

**Comment by Glennmack** [comment]
Hi SamThanks - I’m away this week so will send through by email tomorrow night. CheersGlenn On 13 Apr 2023, at 3:32 pm, Sam Spencer ***@***.***> wrote:﻿
@Glennmack the white boxes was entirely unrelated mate, that was just a UI bug in the editor.
Coming back to your original issue. You've backed up your config, so that's good. I haven't received an email from you, nor is your config attached here. Can you please make sure you have sent it to ***@***.***

**Comment by Glennmack** [comment]
I've rebuilt my entire Bridge4 settings to overcome this issue.
