### ISSUE TITLE
With firmware 1.3.0 update MIDI channel setting on Bridge6 defaults to "Omni"

### ISSUE THREAD

**Issue by Eldritch-Tentacles** [Pirate-MIDI/Pirate-MIDI-BridgeOS#180]
As the title says; after updating and using the editor, my Bridge 6 kept defaulting back to MIDI cannel "Omni" and would/could only be set to my desired MIDI channel (and remain there) by manually setting it via the onboard UI on the device itself.

**Comment by samspencer5991** [comment]
Hey mate, so just to clarify, you mean that if you set the MIDI channel using the editor, it just reverts to OMNI. But setting it onboard the device works fine?

**Comment by Eldritch-Tentacles** [comment]
Yes, that’s exactly it.

**Comment by samspencer5991** [comment]
I've fixed the bug and a patch will be out including this fix next week.
