### ISSUE TITLE
Aux switch ignored on a few banks

### ISSUE THREAD

**Issue by victorcamnerin** [Pirate-MIDI/Pirate-MIDI-BridgeOS#184]
**Device(please complete the following information):**
 - Device: Bridge 4
 - Firmware version: v.1.1.3
 - Hardware version: v1.3.0

**Describe the bug**
I have set up an aux switch with 3 buttons to change banks up and down and one of the buttons to always return to the main page (Bank 0).

What I've discovered is that Bank 65 and Bank 99 ignore the aux switch messages. 

**To Reproduce**
1. Set up an aux switch to handle Bank up, Bank down, and Go to Bank (0).
2. Scroll through to banks 65 or 99.
3. The switches won't work now.

**Expected behavior**
I would expect the aux switches to keep working.

**Additional context**
I've checked the bank aux messages and they are empty. So that should not be an interference.

**Comment by simonaglover95** [comment]
Fixed in BridgeOS 2.0 Release
