### ISSUE TITLE
Momentary Mode doesn't trigger LED on when sending a Smart Message

### ISSUE THREAD

**Issue by Dearxj3gk6** [Pirate-MIDI/Pirate-MIDI-BridgeOS#187]
**Device(please complete the following information):**
 - Device: Bridge4
 - Firmware version:   v1.3.1
 - Hardware version:  v1.1.3

**Describe the bug**
Switch in momentary mode , when press the switch send out smart message, Switch's LED will not turn on .
**To Reproduce**
1. Go to momentary mode 
2. Click on press message 
3. send any smart message  

**Expected behavior**
The Switch in momentary mode , when press the switch send out smart message, Switch's LED will  turn on .

**Screenshots**

**Additional context**

**Comment by simonaglover95** [comment]
I've confirmed this bug and we're looking into it. Thanks for finding it! 👍

**Comment by simonaglover95** [comment]
Fixed in BridgeOS 2.0 Release
