### ISSUE TITLE
Web editor doesn't show Primary action in sequential mode

### ISSUE THREAD

**Issue by Dearxj3gk6** [Pirate-MIDI/Pirate-MIDI-BridgeOS#188]
**Device(please complete the following information):**
 - Device: BridgeOS
 - Firmware version: v1.3.1
 - Hardware version: v1.1.3

**Describe the bug**
Web editor doesn't show Primary action in sequential mode

**To Reproduce**
1. Go to switch 
2. Click on sequential
3. Scroll down to send
4. See error ,doesn't show primary action

**Expected behavior**
Web editor show Primary action in sequential mode

**Screenshots**

**Additional context**

**Comment by simonaglover95** [comment]
Hi there @Dearxj3gk6 I really can't understand what you mean sorry. Can you please add more details, including step-by-step instructions to replicate the issue, and some screenshots or photos would help as well. 
Thanks.
