### ISSUE TITLE
Decrement Step (Sequential) will not trigger Step Messages

### ISSUE THREAD

**Issue by TheGuacamoleXplosion** [Pirate-MIDI/Pirate-MIDI-BridgeOS#193]
**Device**
 - BRIDGE4
 - Firmware version: v1.3.1
 - Hardware version: v1.0.1

**Bug**
While the (absolute) Smart Message “Go-To Step (Sequential)” will go to the defined sequential step AND trigger it, the (relative) Smart Message “Decrement Step (Sequential)” will only go to the sequential step “passively”; i.e. LED colour and display text will change, also further navigation will be starting from that sequential step, but the step’s message stack will not be sent.

Also, when “Decrement Step (Sequential)” is triggered by Secondary Switch Mode “Hold Momentary”, it will often get stuck and not work at all; i.e. even repeated long presses will not result in the desired “Decrement Step” behaviour. You will have to go one step up to make decrement work again. 

**To Reproduce**
At the bottom there’s a config file, FS1 and FS2 of Bank 2 both show the problem. Or:

1. Make a Sequential Mode (Forward, Always, Repeat All) footswitch. 
2. For that footswitch, create a sequence with several steps sending increasing values for the same CC. Like, 
Step1 does nothing, colour black; 
Step2 sends CC#9=0, still black; 
Step3 sends CC#9=21, dark colour;
Step4 sends CC#9=42, slightly brighter colour;
... Step8 sends CC#9=127, white.  
3. Set Secondary Switch Mode for the same footswitch to “Hold Momentary”; and put a “Decrement Step (Sequential)” for that footswitch into the HOLD message stack.
4. Voilà short presses will go forward through the sequence and send CCs; long presses will go backward through the sequence, but not send any CCs. If you try long enough, you will probably also experience the “stuck hold” behaviour described above (Bug part II). 

**Expected behavior**
I want to be able to tweak FX settings with my feet. One footswitch per CC parameter, short press to step up the value, long press to step it down. With the LED colour reflecting the value (CC=0 is black, low CC numbers are dark blue, higher ones are light blue, maximum CC is white). 
Since Scrolling does allow large steps, but will not allow customisation of steps (like, maybe I want to send 0, 15, 40, 75, 127), nor LED colours to change with the values, I went with Sequential mode for this. 
Since “Sequential linked” is not available as secondary function, I went with Smart Messages.

Also, of course, I expect HOLD to always work and not to get stuck :-)

**Additional context**
Commands to “passively” jump to a certain Sequential Step are a great idea in general. But of course, “actively” jumping to Sequential Steps (i.e. going there AND triggering their messages) is even more important.
So, I would suggest to first make sure that all 4 direct Sequential Step Navigation Commands (Reset, Increment, Decrement, GoTo) will work actively (going to the step AND triggering its messages).
In future firmware updates, additional smart messages for passive navigation would be great; like “Decrement Step (Sequential), no messages sent“. 

Config file (renamed to .txt since github won’t allow .json):
[Bridge 4_2023-06-09_09-52-29_controlv7++.txt](https://github.com/Pirate-MIDI/Pirate-MIDI-BridgeOS/files/11704489/Bridge.4_2023-06-09_09-52-29_controlv7%2B%2B.txt)

**Comment by simonaglover95** [comment]
Fixed in BridgeOS 2.0 Release
